language: php

php:
  - 7.1
  - 7.3

sudo: false

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0
    - php: 7.1
      env: PHPSTAN=1 DEFAULT=0
    - php: 7.1
      env: PREFER_LOWEST=1

before_install:
  - echo 'extension = ldap.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - if [[ $PREFER_LOWEST != '1' ]]; then composer install --prefer-dist --no-interaction; fi
  - if [[ $PREFER_LOWEST == '1' ]]; then composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

before_script:
  - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi
  - if [[ $PHPSTAN == 1 ]]; then composer require --dev phpstan/phpstan:"^0.9"; fi

script:
  - if [[ $DEFAULT == 1 && $TRAVIS_PHP_VERSION == 7.3 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ $DEFAULT == 1 && $TRAVIS_PHP_VERSION != 7.3 ]]; then vendor/bin/phpunit; fi

  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/; fi
  - if [[ $PHPSTAN == 1 ]]; then vendor/bin/phpstan analyse -l 4 src; fi

after_success:
  - if [[ $DEFAULT == 1 && $TRAVIS_PHP_VERSION == 7.3 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
